config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/index'
  get 'post/new'
  root 'static_pages#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#delete'

  resources :posts, only: [:new, :create, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  # before_create :remember
  has_secure_password
  has_many :posts
  # ADD VALIDATION
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(token)
    BCrypt::Password.new(remember_digest).is_password?(token)
  end

  def self.encrypt(token)
    # Digest::SHA1.hexdigest(token.to_s)

    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(token, cost: cost)
  end
 
  # Set remember_token
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.encrypt(remember_token))
  end

  # Remove remember_token
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :logged_in?

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end


# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def sign_out
  	forget(current_user)
  	session.delete(:user_id)
  	@current_user = nil
  end

  def logged_in?
  	!current_user.nil?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create 
    @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to posts_path
      else 
        render 'new'
      end
  end

  def index
    @posts = Post.all
  end


  def logged_in_user
    unless logged_in? 
      redirect_to login_url
    end
  end

end

private
  def post_params
    params.require(:post).permit(:title, :content)
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    render 'new'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      # remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url
    else
      # Create an error message.
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def delete
    sign_out if logged_in?
    redirect_to login_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # redirect_to @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#member-nav" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "members-only", root_path,class: 'navbar-brand' %>
        </div>

      <div class="collapse navbar-collapse" id="member-nav">
        <ul class="nav navbar-nav navbar-right">
          
          <% unless logged_in? %>
            <li>
            <%= link_to "Sign up", signup_path %>
            </li>
            <li>
              <%= link_to "Login", login_path %>
            </li>
          <% end %>
          <li>
            <%= link_to "All Posts", posts_path %>
          </li>
          <% if logged_in? %> 
            <li>
              <%= link_to "New Post", posts_new_path %> 
            </li>
             <li>
              <%= link_to "Logout", logout_path, method: :delete, class: "logout" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Members Only</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <%= yield %>

    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="posts">
  <div>
    <h3 class="post"><%= post.title %></h3>
    <% if logged_in? %>
    	<h4 class="author">
    		<%= User.find_by(id: post.user_id).name  %>
    	</h4>
    <% end %>
    <p><%= post.content %></p>
  </div>
</div>
<hr>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<h1>Posts</h1>

<%= render @posts %>

app/views/posts/new.html.erb
<% provide(:title, 'Create new Post') %>
<h1>Create new Post</h1>
<div class="form-container">
	<%= form_for(@post, url: posts_path) do |f| %>

	    <%= f.label :title %>
	    <%= f.text_field :title, class: 'form-control' %>
	    <br>
	    <%= f.label :content %>
	    <%= f.text_area :content, size: '50x10', class: 'form-control' %>
	    <br>
	    <%= f.submit "Create Post", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Welcome</h1>



<div class="jumbotron">
  <h2>Hello, member</h2>
  <p>Welcome to members-only exclusive blog</p>   
  <% unless logged_in? %>
    <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Login", login_path, class: "btn btn-primary btn-lg" %>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Create new Post", posts_new_path, class: "btn btn-primary btn-lg" %> 
    <%= link_to "View all Posts and it's Author", posts_path, class: "btn btn-primary btn-lg" %>
<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="form-container">
<%= form_for(@user, url: signup_path) do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <br>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <br>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>